spring:
  profiles:
    active: dev

  datasource:
    username: root
    password: root
    url: jdbc:mysql://HOST:3306/life-exercise?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

  rabbitmq:
    host: 192.168.0.0
    port: 5672
    username: username
    password: password
    ssl:
      enabled: false

application:
  rabbit:
    queues:
      events: exercises