spring:
  profiles:
    active: dev

  jpa:
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: false
        show_sql: false

  datasource:
    username: root
    password: root
    url: jdbc:mysql://HOST:3306/life-exercise?createDatabaseIfNotExist=true&serverTimezone=America/Sao_Paulo

  rabbitmq:
    host: 192.168.0.0
    port: 5672
    username: username
    password: password
    ssl:
      enabled: false

application:
  academy.minimum.minutes: 20
  rabbit:
    queues:
      exercises: exercises
      tracking: person_tracking