name: publish

on:
  push:
    branches: main

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Build application
        run: ./gradlew build
      -
        name: Login in ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and Push Docker image
        run: |
          docker buildx create --use --name mybuilder
          docker buildx build . --platform linux/amd64,linux/arm64 --tag ghcr.io/alves-dev/life-exercises:latest --push
          docker buildx build . --platform linux/amd64,linux/arm64 --tag ghcr.io/alves-dev/life-exercises:$(date +%Y%m%d) --push